
services:
  {{cookiecutter.project_slug}}_db:
    image: postgres
    env_file:
      -  {{cookiecutter.project_slug}}/.env
    container_name: {{cookiecutter.project_slug}}_db
    expose:
      - 5432
    volumes:
      - {{cookiecutter.project_slug}}_pgdata:/var/lib/postgresql/data

    networks:
      - {{cookiecutter.project_slug}}_network

  {{cookiecutter.project_slug}}_service:
    build:
      context: {{cookiecutter.project_slug}}
      dockerfile: ./Dockerfile
    volumes:
      - ./{{cookiecutter.project_slug}}/src:/src
    env_file:
      - {{cookiecutter.project_slug}}/.env
    environment:
      POSTGRES_HOST: {{cookiecutter.project_slug}}_db

    depends_on:
      - {{cookiecutter.project_slug}}_db
    container_name: {{cookiecutter.project_slug}}_service
    expose:
      - 80
    networks:
      - {{cookiecutter.project_slug}}_network


volumes:
  {{cookiecutter.project_slug}}_pgdata: {}

networks:
  {{cookiecutter.project_slug}}_network:
